### ISSUE TITLE
Nest Thermostat reporting 75F constantly

### ISSUE THREAD

**Issue by ttaidapos** [jakeday/WinkDashboard#1]
![issue](https://cloud.githubusercontent.com/assets/27898709/25306982/7a620956-275e-11e7-9a8f-0ee8a4678c60.png)

Tried adding removing using Wink but no luck, also tried to refresh.

**Comment by jakeday** [comment]
Wink is separating the "set" temperature to min for heating and max for cooling. Looks like I'm just reading the max across the board, which results in the wrong temperature being displayed. I'll get this updated and add support for setting the mode as well.

**Comment by jakeday** [comment]
This is fixed with the most recent commits.
