### ISSUE TITLE
Robot that doesn't exist gets listed

### ISSUE THREAD

**Issue by ttaidapos** [jakeday/WinkDashboard#2]
I have tried on a fresh install, removed all robots, and it still shows.  The robot "Aux Active Alert" is showing but doesn't exist on any Wink account.
![issue 2](https://cloud.githubusercontent.com/assets/27898709/25307037/e5bfeed8-275f-11e7-8dd3-23a266c81370.png)

**Comment by jakeday** [comment]
Some events have robots setup as kind of background services that are hidden from the official Wink app. I'll try to hide these in the next update to accurate reflect what you see there.

**Comment by jakeday** [comment]
This is resolved with the latest commits.
